name: Simple Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      job:
        description: 'Select a job to run manually'
        required: true
        type: choice
        options:
          - job2
          - job3

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Print message
        run: echo "Job 1 is running automatically on push to main"

  job2:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'job2'
    steps:
      - name: Print message
        run: echo "Job 2 is running manually"

  job3:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'job3'
    steps:
      - name: Print message
        run: echo "Job 3 is running manually"
