name: Deploy Node.js API

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - push-to-dockerhub
          - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'build')

    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build -t bharath7898/my-api:latest .

  push-to-dockerhub:
    runs-on: ubuntu-20.04
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'push-to-dockerhub'

    steps:
      - name: Debug Inputs
        run: echo "Job selected: ${{ github.event.inputs.job }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag bharath7898/my-api:latest bharath7898/my-api:v1.0.4
          docker push bharath7898/my-api:v1.0.4

  deploy-to-ec2:
    runs-on: ubuntu-20.04
    needs: push-to-dockerhub
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'deploy-to-ec2'

    steps:
      - name: Debug Inputs
        run: echo "Job selected: ${{ github.event.inputs.job }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST <<EOF
            sudo dnf update -y
            sudo dnf install docker -y
            sudo systemctl start docker
            sudo usermod -a -G docker $EC2_USER
            sudo systemctl enable docker
          EOF

      - name: Restart SSH Session and Deploy
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST <<EOF
            docker pull bharath7898/my-api:v1.0.4
            docker stop my-api || true
            docker rm my-api || true
            docker stop mongo || true
            docker rm mongo || true
            docker run -d --name mongo -v mongo-data:/data/db -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=admin -e MONGO_INITDB_DATABASE=mydatabase -p 27017:27017 mongo:4.4.6
            docker run -d --name my-api -p 80:3000 --link mongo -e MONGODB_URI=mongodb://admin:admin@mongo:27017/mydatabase?authSource=admin bharath7898/my-api:v1.0.4
          EOF
